### ISSUE TITLE
Article template: Ability for content team to publish a basic article

### ISSUE THREAD

**Issue by calexity** [cal-itp/mobility-marketplace#189]
As the content team,
I want to be able to create a new article page
So that I can compose an article
And share it with transit providers via a unique link

---

This story includes
- A way for content team to add a new page
- Ability to title the article page
- Ability to input author's name OR netlify determines author by who is logged in
- Ability to write or edit the URL path
- Ability to add plain text content to the body of the article
- Ability to publish the page and view it by going to the unique link

**Resources**
- [Design in Figma ](https://www.figma.com/file/QR2c1HOhrJptQbN0FSfu9J/Mobility-Marketplace?node-id=2311%3A9328)(see Design 1.2 Release)

**QA**
- Kurtis will get to PR, which will include a deploy preview link
- @calexity will assist Harrison and Jess in accepting the completed story

**Comment by thekaveman** [comment]
Closing for now. We don't have an article template any longer.
