### ISSUE TITLE
Article template: Ability to set up authors

### ISSUE THREAD

**Issue by calexity** [cal-itp/mobility-marketplace#192]
As the content team,
When I am writing an article
I want to be able to select from a list of authors
So the names are consistent across articles and so we can later add author bios.

--

This story includes

- Ability to add a name to a list of authors
- Ability to select an author when writing a post

**Comment by thekaveman** [comment]
The Authors collection already exists, under Metadata (could be moved if that is confusing): https://github.com/cal-itp/transit-stop/blob/dev/admin/config.yml#L343

Adding an Author selector to Articles is as simple as adding a `relation` widget in the config, like we do for Calls to Action e.g. on the homepage: https://github.com/cal-itp/transit-stop/blob/dev/admin/config.yml#L114

**Comment by calexity** [comment]
Excellent! We couldn't figure out how to create an article so we couldn't see this option yet but - would you call this complete? No dev work left?

**Comment by thekaveman** [comment]
Closing for now. We don't have an article template any longer.
