### ISSUE TITLE
Article template: Restyling

### ISSUE THREAD

**Issue by calexity** [cal-itp/mobility-marketplace#194]
This is a story to restyle the article to match our new template. The previous iteration was in the state template styles and it needs to be updated per the mock below 

**Resources**
- [Design in Figma ](https://www.figma.com/file/QR2c1HOhrJptQbN0FSfu9J/Mobility-Marketplace?node-id=2311%3A9328)(see Design 1.2 Release)

**QA**
- Kurtis will get to PR, which will include a deploy preview link
- @calexity will assist Harrison and Jess in accepting the completed story

**Comment by thekaveman** [comment]
Closing for now. We don't have an article template any longer.
