### ISSUE TITLE
Page template: Ability to add citation

### ISSUE THREAD

**Issue by calexity** [cal-itp/mobility-marketplace#196]
As the content team,
I want to be able to add a citation to a piece of text
So that I can include a reference without linking it in the body of the text

----
This story includes
- A way for content team to add a citation to part of the body text
- The citation should add a superscript number (as shown in mock)
- When a citation is added, a "References" section should be added with a corresponding number
- The citation should also take the content creator to the References section so they can add their citation

**Design in Figma (see Design 1.1 Release)**
https://www.figma.com/file/QR2c1HOhrJptQbN0FSfu9J/Mobility-Marketplace?node-id=2330%3A9477

**Comment by calexity** [comment]
We'll need to discuss this in our web planning meeting. It's somewhat unconventional to link citations like this and I looked into accessibility/usability concerns. Here's an option I think can work (minus the yellow highlighting):

**Comment by thekaveman** [comment]
Closing. We don't have a CMS configured right now.
