### ISSUE TITLE
host email signatures

### ISSUE THREAD

**Issue by vykster** [cal-itp/mobility-marketplace#203]
> First, do we have a place where we can host email signature files? They are currently embedded from where Colleen saves them on her web hosting, but to prevent the link getting broken she thinks it makes more sense for us to host them. She wasn't sure what the best solution was so wanted to flag.

**Comment by krainboltgreene** [comment]
What is a "email signature file", if it's just a file then #190 is the solution.

**Comment by thekaveman** [comment]
@vykster is this still a need/concern? Can we please close if not?

**Comment by thekaveman** [comment]
And if we do still need it, the work from #312 can be leveraged to host signature files at resources.calitp.org

**Comment by vykster** [comment]
I have no idea. might be worth checking back in with Colleen Corcoran? Or
asking someone who's using the signature now? I believe the issue before
was that Colleen was hosting the files herself for us.

**Comment by machikoyasuda** [comment]
I'm guessing this issue is no longer necesary, so might be good to close it. 

cc @mrose914
