### ISSUE TITLE
Pages should have some built-in bottom margin

### ISSUE THREAD

**Issue by calexity** [cal-itp/mobility-marketplace#256]
Existing: https://www.camobilitymarketplace.org/about

Desired: some space between end of main page content and footer (approx 3-4x the footer height or 75px roughly)

<img width="1338" alt="existing" src="https://user-images.githubusercontent.com/1103366/110738856-e0dc6980-81e4-11eb-9f05-d61ce8e258ac.png">
<img width="1341" alt="desired" src="https://user-images.githubusercontent.com/1103366/110738866-e5a11d80-81e4-11eb-90ca-8632678aa713.png">

**Comment by allejo** [comment]
Fixed by #275
