### ISSUE TITLE
Re-license under AGPLv3

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#257]
AGPLv3 is more appropriate for websites/webapps.

**Comment by krainboltgreene** [comment]
Great point, though I can't help but suggest also [the Hippocratic license](https://firstdonoharm.dev/).

**Comment by allejo** [comment]
As we're approaching the target-ish deadline for the next milestone. @thekaveman @vykster, any updates on what the license for this website will be?

**Comment by thekaveman** [comment]
Oops, didn't see this until now @allejo. Yes we will use AGPLv3.
