### ISSUE TITLE
Hero image distorted on iPhones

### ISSUE THREAD

**Issue by harrisonpeck** [cal-itp/mobility-marketplace#265]
I opened MobiMart on my iPhone and noticed that the hero image (the one with a woman and child looking at a phone in a bus stop) is all distorted, in both vertical and horizontal views. Vertical screenshot below. 

![image](https://user-images.githubusercontent.com/80477201/116286935-cb53dc80-a75d-11eb-8cc8-3e7524d20776.png)

**Comment by allejo** [comment]
Looks like it's a Webkit bug, it's happening on Safari on desktop too

![image](https://user-images.githubusercontent.com/1246453/116289289-38a84300-a747-11eb-86fa-5e46d20d487d.png)

**Comment by allejo** [comment]
Fixed by #275
