### ISSUE TITLE
CSS updates to new Mobimart screens

### ISSUE THREAD

**Issue by kristigrassi** [cal-itp/mobility-marketplace#290]
Hey @allejo 

I've marked up a few screens in Figma with some CSS changes. I think it's pretty straightforward but let me know if you have questions or feedback

https://www.figma.com/file/ZLusI4KvrVeIZw5GBLvvKb/Procurement-Flow?node-id=329%3A606

**Comment by allejo** [comment]
> margin between bottom of nav text and top of header text should be 110px. Assuming these changes will apply to the contracts table screen as well.

This is approximately ~110px from the bottom of the nav text to the top of the first element on each page.

![image](https://user-images.githubusercontent.com/1246453/125384502-e04c0f00-e34d-11eb-895c-5ac069325965.png)
![image](https://user-images.githubusercontent.com/1246453/125384526-e7731d00-e34d-11eb-9a29-d008feea1002.png)

The CA Gov theme has some magic for making the navigation bar "just right," so this is as close as I can get it.

- What should the gap size be on mobile? Still 110px or less?
- Should this rule apply to pages that have banners like the "Go Contactless" page?

**Comment by kristigrassi** [comment]
Hey @allejo 

- It should not apply to pages that have banners like the "Go Contactless" page
- On mobile let's do 60px
