### ISSUE TITLE
Review our CMS configuration

### ISSUE THREAD

**Issue by allejo** [cal-itp/mobility-marketplace#294]
Looks like our CMS integration is (partially?) broken and doesn't even have invitation/password requests work.

> For successful use of the `{{ .ConfirmationURL }}` variable, your site landing page must include the [Identity widget](https://github.com/netlify/netlify-identity-widget). If the Identity widget is not on the landing page, you must customize the path the emails link to so that visitors are sent to a page that includes the widget.

https://docs.netlify.com/visitor-access/identity/identity-generated-emails/#custom-templates

**Comment by thekaveman** [comment]
We're not using the CMS right now. Closing.
