### ISSUE TITLE
Edit to Dataset page on MobiMart

### ISSUE THREAD

**Issue by aialvarado** [cal-itp/mobility-marketplace#296]
We got some feedback from LADOT about the dataset page. They requested 'DASH' be changed to the Los Angeles Department of Transportation. 
<img width="1440" alt="Screen Shot 2021-07-19 at 1 43 46 PM" src="https://user-images.githubusercontent.com/85589449/126379410-664d3dde-e124-449a-9ec5-c38a8f314d58.png">

**Comment by thekaveman** [comment]
Just a heads up @allejo - @aialvarado and I chatted about this. Ideally we'll get it solved for good when we finish up #268 (since this value has been corrected in the data). This is just a temporary manual edit to address the feedback in the meantime.
