### ISSUE TITLE
New RFP deadline date on Homepage

### ISSUE THREAD

**Issue by aialvarado** [cal-itp/mobility-marketplace#298]
Hi there - We need to change the following copy on the homepage and anywhere we talk about the RFP deadline to reflect the new date - 9/6.

Payment system RFP, hot off the press!
California just moved one big step closer to contactless fare collection with the release of a final Request for Proposals (RFP) for fare validators (payment acceptance devices) and fare calculation software (transit processor). Final Proposals are due by 5:00 PM Pacific Time on September 6, 2021.

**Comment by allejo** [comment]
The only reference I saw is on the homepage. Let me know if there are any others that I didn't see!
