### ISSUE TITLE
Newer RFP deadline date on Homepage

### ISSUE THREAD

**Issue by esquared415** [cal-itp/mobility-marketplace#299]
Hello again! We need to make a one-character change to the following copy on the homepage to reflect the new-new RFP deadline: 9/7 (still at 5p Pacific).

So that revised text would read:

Payment system RFP, hot off the press!
California just moved one big step closer to contactless fare collection with the release of a final Request for Proposals (RFP) for fare validators (payment acceptance devices) and fare calculation software (transit processor). Final Proposals are due by 5:00 PM Pacific Time on September **7**, 2021.

Thanks so much!

**Comment by allejo** [comment]
Changed in aad50918e98dcd6b013f7d2b7a0c2ef929380e94 :smile:
