### ISSUE TITLE
New "RFP" blurb for Homepage

### ISSUE THREAD

**Issue by esquared415** [cal-itp/mobility-marketplace#307]
_On Mobi Mart's Homepage, in the same position where we previously had the "Payment system RFP, hot off the press!" blurb, please mock up (but do not deploy) the following text:_

**Contactless payment systems: Contracts update!**
U.S. public transit providers, we have news for you: Modernizing your fleet to accept riders’ debit/credit card fare payments is one step closer with DGS’s Notice of Intent to Award contracts for open-loop contactless fare validators (payment acceptance devices) and fare calculation software (transit processor services). View that Notice [here](https://www.dgs.ca.gov/PD/Resources/Page-Content/Procurement-Division-Resources-List-Folder/Award-Notifications) under Intent to Award: December 2021—look for Event ID# 5217028.

_Once staged text is available, please pass the staging site's URL to @esquared415 to pass to GG to circulate for approval. Thanks so much!_

**Comment by esquared415** [comment]
Circling back with updated text to replace the blurb seen [here](https://deploy-preview-308--cal-itp-transit-stop.netlify.app/). Please swap in:

**### Contactless payment systems: Contracts available!**
U.S. public transit providers, we have news for you: Modernizing your fleet to accept riders’ debit/credit card fare payments is now possible with DGS’s award of Master Service Agreements (MSAs) for open-loop contactless fare validators (payment acceptance devices) and fare calculation software (transit processor services). See our [Contracts](https://camobilitymarketplace.org/contracts) page for more info and to view MSAs.

**Comment by angela-tran** [comment]
> Apologies for the delayed reply, @angela-tran!
> 
> This looks really good—except that I had a late-breaking request to remove "DGS's" in favor of saying "the State of California’s" in the "RFP blurb." 
> 
> The new text we've agreed upon is indicated with _ital_ below (but should appear in roman):
> 
> **Contactless payment systems: Contracts update!**
> U.S. public transit providers, we have news for you: Modernizing your fleet to accept riders’ debit/credit card fare payments is now possible with _the State of California’s_ award of Master Service Agreements (MSAs) for open-loop contactless fare validators (payment acceptance devices) and fare calculation software (transit processor services). See our [Contracts](https://www.camobilitymarketplace.org/contracts/) page for more info and to view MSAs.
> 
> 
> **Thank you!**

_Originally posted by @esquared415 in https://github.com/cal-itp/mobility-marketplace/issues/308#issuecomment-1040059304_
