### ISSUE TITLE
Reconfigure resources.calitp.org as GCS bucket

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#312]
We want to host assets and files under this domain, but the web content (e.g. links to the resources) will live on the MobiMart site.

- [x] archive the [`resources`](/cal-itp/resources) repository
- [x] set up GCS bucket for `resources.calitp.org` following the [implementation notes for `gtfs.calitp.org`](https://docs.google.com/document/d/1mlc__XCSKyYI8mOLLhZ6nipX2tAYH7EHuPOecTgInl0/edit#heading=h.7x11jlb19919)
- [x] create an `index.html` file at the root of the bucket that redirects the user to `camobilitymarketplace.org/resources` (see https://en.wikipedia.org/wiki/Meta_refresh for more on how this can be done on the client)

**Comment by thekaveman** [comment]
Moved this to another issue, not needed to close this one: #317

**Comment by angela-tran** [comment]
@thekaveman and I verified that the domain points to the right GCS bucket and that the bucket works.
