### ISSUE TITLE
Document logging in, editing files etc. in the Resources bucket

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#317]

**Comment by machikoyasuda** [comment]
Documenting it here for now -

Requirements: User must be authorized on Google Cloud to access the `resources-calitp-org` bucket.

1. Go to https://cloud.google.com/
2. Click `Console`
3. Click `Cloud Storage`
4. Click `resources.calitp.org`
5. Click `mobility-marketplace`
6. Click button for action needed: `Upload Files`, `Delete` or `Edit` on a particular file
