### ISSUE TITLE
/Resources page -- where to find page Content + Docs to link to

### ISSUE THREAD

**Issue by esquared415** [cal-itp/mobility-marketplace#323]
For [/resources](https://deploy-preview-320--cal-itp-transit-stop.netlify.app/resources), we are awaiting approval of the page's:
• [Content](https://docs.google.com/document/d/1Os7U_LNEuJwJbEB2Yde5tkIeEWb2NyN97Tny1YCM3bI/edit#): @o-ram or Zack will @ tag you on this ticket in #websites-notify channel when Content is approved and ready to add to page; _please wait to access this GDoc and copy over content until you get their_ 👍
• [MSA Onboarding Docs](https://drive.google.com/drive/folders/1hG5JBaObW7qxHUKLZhR_2UVswY_1mqIH?usp=sharing) to link to within Content's text blocks: @o-ram or Zack will @ tag you on this ticket in #websites-notify channel when Docs are approved and ready to link to Content; _please wait to access this GDrive folder's Docs until you get their_ 👍

(And thank you for already dropping "Resources" from the nav bar!)

Thanks so much!

**Comment by o-ram** [comment]
@thekaveman @angela-tran @machikoyasuda 

Update! The **content** for the [Resources page](https://deploy-preview-320--cal-itp-transit-stop.netlify.app/resources) has been approved and is ready to be added. The **onboarding docs** we want to link to are still awaiting DGS final approval. Gillian has requested the page go live by/on Tuesday (3/1) morning though, so I wanted to give you all that heads up given how soon that is.

Therefore, could you please set aside time to add the content in [this doc](https://docs.google.com/document/d/1Os7U_LNEuJwJbEB2Yde5tkIeEWb2NyN97Tny1YCM3bI/edit#) to the page on Monday? I've been assured that the onboarding docs will be in your hands Monday as well, so I will pass those along to you all ASAP to plug into the page (we are trying to give as much time as possible for last minute DGS edits to come through, but I'll make sure you have them as soon as I can)

Thank you _so_ much!

**Comment by esquared415** [comment]
@angela-tran All 4 docs (3 PDFS + 1 Excel workbook) are now ready for upload from this folder: [MSA Onboarding Docs](https://drive.google.com/drive/folders/1hG5JBaObW7qxHUKLZhR_2UVswY_1mqIH?usp=sharing)

I tried to name the files with the body text you'll be hyperlinking on /resources page.

Please shout if you have any Qs! And thanks ever so much!!
