### ISSUE TITLE
/resources page: replace 1 PDF

### ISSUE THREAD

**Issue by esquared415** [cal-itp/mobility-marketplace#329]
Hi again! We had a problem with some links within the Info Packet PDF. This revised version fixes that issue. 

Please upload the following revised PDF to replace "Contactless Payments MSA Information Packet (PDF)":
[Contactless Payments MSA Info Packet_2022.03.02.pdf](https://github.com/cal-itp/mobility-marketplace/files/8172671/Contactless.Payments.MSA.Info.Packet_2022.03.02.pdf)

Let me know if you have any Qs. And thank you @thekaveman / @angela-tran / @machikoyasuda ! : )

**Comment by angela-tran** [comment]
@esquared415 The PDF should be updated on the live site now! Please confirm whenever convenient that it's what you expect 😄

**Comment by esquared415** [comment]
Perfection—thank you so much!!
