### ISSUE TITLE
[Feature Request]: Live Chat for services

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/mobility-marketplace#355]
### Feature or Question

Feature

### Request

Add the `Live Chat` feature to Hubspot: https://knowledge.hubspot.com/chatflows/create-a-live-chat

### Is this request related to a problem?

Not being able to respond to questions fast enough as they have to go through the support pipeline and emailed back to them.

### Use Case

Respond to less complicated questions faster.

### Additional Info

N/a

**Comment by thekaveman** [comment]
@mrose914 you may not have enough access to the `crm-helpdesk` repo... will check on that.

**Comment by AnthonyRollins** [comment]
@thekaveman In case you need it, there are two places where you can edit the settings for Hubspot Live chat:
- [Inbox Settings](https://app.hubspot.com/live-messages-settings/5519226/inboxes/318528/edit/live-chat/primary/configure)
- [Chatflow under Conversations](https://app.hubspot.com/chatflows/5519226/edit/live-chat/5546599/build)

Let me know if you want to grab some time today - I have some availability
