### ISSUE TITLE
Add event tracking for MobiMart in Amplitude

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#356]
**Request**
We would like to implement basic event tracking for the [Mobility Marketplace](https://www.camobilitymarketplace.org/). While we know that some of the events may change over time with our planned redesign, we would like to establish a baseline based on existing events and begin building funnels. 

See tab "Event Tracking Amplitude" for details of the events https://docs.google.com/spreadsheets/d/1kHrvfI0pa3NFvLa63JvM1zl9gyxJET5Bxn9sxoHEj6c/edit#gid=144103548

NOTE: I did not name the events but I can. I would defer to the implementor to name them in line with any existing frameworks but happy to suggest names if it's helpful.

**Comment by thekaveman** [comment]
@mrose914 I reviewed the spreadsheet and left a few comments.

My overall thought is we can do most of what is on that spreadsheet with just a couple events:

* `viewed page`
* `clicked link`

With each event, we would send context information like the page that was viewed or the link/URL that was clicked. 

Within Amplitude we can create "custom events" that filter down the generic events above into more specific things we want to track, like landing pages or form submissions.

I still need to look into the form submission errors event/idea.

**Comment by thekaveman** [comment]
Created a new Amplitude project [Mobility Marketplace](https://data.amplitude.com/compiler/Mobility%20Marketplace/events/main/latest) and started to define our basic events in the Tracking Plan.

**Comment by thekaveman** [comment]
After fumbling through the docs on [setting up `ampli` with the newer Typescript-based `@amplitude/analytics-browser` NPM package](https://www.docs.developers.amplitude.com/data/sdks/typescript-ampli/)... 

We decided to stick with the legacy `amplitude-js` snippet for now.

**Comment by thekaveman** [comment]
Using [Netlify Snippet Injection](https://docs.netlify.com/site-deploys/post-processing/snippet-injection/) to inject the `amplitude-js` snippet into the `<head>`.

Doing this in Netlify rather than in the source code allows us to determine the `CONTEXT` - which will be `production` only for deploys from the `main` branch. This way we can configure deploy previews to send events to the Development environment in Amplitude.

Here's the snippet:

```html
<script type="text/javascript">
(function(e,t){var r=e.amplitude||{_q:[],_iq:{}};var n=t.createElement("script")
;n.type="text/javascript"
;n.integrity="sha384-6T8z7Vvm13muXGhlR32onvIziA0TswSKafDQHgmkf6zD2ALZZeFokLI4rPVlAFyK"
;n.crossOrigin="anonymous";n.async=true
;n.src="https://cdn.amplitude.com/libs/amplitude-8.18.4-min.gz.js"
;n.onload=function(){if(!e.amplitude.runQueuedFunctions){
console.log("[Amplitude] Error: could not load SDK")}}
;var s=t.getElementsByTagName("script")[0];s.parentNode.insertBefore(n,s)
;function i(e,t){e.prototype[t]=function(){
this._q.push([t].concat(Array.prototype.slice.call(arguments,0)));return this}}
var o=function(){this._q=[];return this}
;var a=["add","append","clearAll","prepend","set","setOnce","unset","preInsert","postInsert","remove"]
;for(var c=0;c<a.length;c++){i(o,a[c])}r.Identify=o;var u=function(){this._q=[]
;return this}
;var p=["setProductId","setQuantity","setPrice","setRevenueType","setEventProperties"]
;for(var l=0;l<p.length;l++){i(u,p[l])}r.Revenue=u
;var d=["init","logEvent","logRevenue","setUserId","setUserProperties","setOptOut","setVersionName","setDomain","setDeviceId","enableTracking","setGlobalUserProperties","identify","clearUserProperties","setGroup","logRevenueV2","regenerateDeviceId","groupIdentify","onInit","logEventWithTimestamp","logEventWithGroups","setSessionId","resetSessionId","setLibrary","setTransport"]
;function v(e){function t(t){e[t]=function(){
e._q.push([t].concat(Array.prototype.slice.call(arguments,0)))}}
for(var r=0;r<d.length;r++){t(d[r])}}v(r);r.getInstance=function(e){
e=(!e||e.length===0?"$default_instance":e).toLowerCase()
;if(!Object.prototype.hasOwnProperty.call(r._iq,e)){r._iq[e]={_q:[]};v(r._iq[e])
}return r._iq[e]};e.amplitude=r})(window,document);
  {% if CONTEXT == 'production' %}
  amplitude.getInstance().init("production API key");
  {% else %}
  amplitude.getInstance().init("development API key");
  {% endif %}
</script>
```

See the configuration at: https://app.netlify.com/sites/cal-itp-mobility-marketplace/settings/deploys#post-processing
