### ISSUE TITLE
Add new /how-to/go-contactless page

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#372]
We are creating a new page https://www.camobilitymarketplace.org/how-to-go-contactless that will serve as the one-stop-shop for information about how to go contactless, including links to resources.

**Comment by thekaveman** [comment]
Given that we anticipate introducing more of a structure to these pages (and we'll have more of them) - what do you think about a slightly more structured URL pattern: `/how-to/go-contactless`

Then we can have: `/how-to/get-connected` (or whatever)

**Comment by machikoyasuda** [comment]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/3673236/199066965-e5ed5cb5-1f06-48f0-bee6-19e8291a5f15.png">
