### ISSUE TITLE
Add new blurb to /contracts page about GTFS compliance

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#376]
New design here: https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=3979%3A11994

Copy here: We recommend creating an action plan for becoming GTFS-ready before going contactless, as the vendors you select can help you use this data for reporting purposes plus help your customers see your real-time vehicle location and fare information on journey-planning smartphone maps and apps.

**Comment by machikoyasuda** [comment]
@mrose914 Does this ticket include adding this header text as well?
<img width="332" alt="image" src="https://user-images.githubusercontent.com/3673236/206033860-5351b718-c4f2-475b-9b46-b476c1b86a16.png">
