### ISSUE TITLE
Enable reCAPTCHA on all forms

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#378]

**Comment by thekaveman** [comment]
@segacy1 here's more on reCAPTCHA's guidance around hiding the branding and what requirements there are if we do that: https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed

**Comment by thekaveman** [comment]
@mrose914 @machikoyasuda some more context as I've been looking in to this today...

reCAPTCHA does not work without a backend server. Whether the challenge is presented to the user (i.e. "Check this box to indicate you are human" or "Click each picture of a school bus") or is invisible / in the background, we still need to take the response from that challenge and send it to Google to verify. And this can't happen in the browser / in JavaScript -- it must happen from a server.

Mobi Mart is a static website, meaning there is no backend server and everything is delivered/running the user's browser. Netlify (the web host) has features to allow us to do backend server type processes, and we could also do it from another cloud service like Google or AWS or Azure. This will take more time to set up though.

**Comment by machikoyasuda** [comment]
Is there a decision made about whether we need reCAPTCHA on Mobi Mart for this Milestone (now target due date 12/15)?

It looks like this on production right now

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/206047394-14c50e00-ea92-4111-9f16-62f6c0681ebc.png">


The reCAPTCHA icon overlaps with the Hubspot icon, and gets close to the Page Up icon (that comes from the CA Web Std Template).

**Comment by thekaveman** [comment]
I think we should not try and handle this for December. It will be introducing a brand new concept/service for the website (the backend Netlify/cloud "function" to do the Google reCAPTCHA verification) and I'd rather we had some time to think and plan for that. The other consideration now is cost: this might not be free anymore.

**Comment by machikoyasuda** [comment]
Gotcha. Removing this ticket from the Contactless V2 Milestone and closing it for the time being.

@thekaveman Do you know why reCAPTCHA is showing up on https://www.camobilitymarketplace.org/go-contactless now? I can make a new ticket to disable it.
<img width="321" alt="image" src="https://user-images.githubusercontent.com/3673236/206061234-32f704f9-45b6-4f01-8e6d-39e10a16193f.png">

**Comment by thekaveman** [comment]
@machikoyasuda that is coming from the Constant Contact form! I'm not sure if we'd want to disable/remove it from there. Maybe we can hide it and add the text instead, per their branding guide?

<img width="838" alt="image" src="https://user-images.githubusercontent.com/1783439/206066071-a35c5a19-c4fe-4ac0-ad2c-2c905be793ba.png">

**Comment by thekaveman** [comment]
@mrose914 I think it's OK to be closed. Especially now that we are transitioning to Hubspot forms, there is probably more spam protection built-in there (or maybe even reCAPTCHA config we could look into). @AnthonyRollins do you know if Hubspot forms have anything like this?

But I think we decided that the engineering effort to setup a backend to validate reCAPTCHA on a static website would require a lot more research and planning. Can we wait to see what happens with the Hubspot forms and maybe revisit then?

**Comment by AnthonyRollins** [comment]
@thekaveman All forms have a reCAPTCHA added; let me know if you can't see that on your end.

**Comment by thekaveman** [comment]
@machikoyasuda FYI
