### ISSUE TITLE
Updates to navigation for Go Contactless V2

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#400]
Updates requested: 

- From https://www.camobilitymarketplace.org/go-contactless, GET STARTED button should take you to our guide (https://www.camobilitymarketplace.org/how-to/go-contactless)
- From https://www.camobilitymarketplace.org/how-to/go-contactless, replace GET STARTED button with a VIEW GUIDE button that should drop you down to the guide below (on same page)
- Update button text to be sentence case here https://www.camobilitymarketplace.org/go-contactless so that "Get Started" reads "Get started" and "Contact Us" reads "Contact us"

**Comment by esquared415** [comment]
@mrose914 @segacy1 Yes, these edits look great and cover all that we discussed. Thanks ever so much!

CC @o-ram, for awareness

**Comment by segacy1** [comment]
@mrose914 Updated [/go-contactless](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=4494%3A19496&t=ZaOdyx4fdZjQ3mO6-4) and [/how-to/go-contactless](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=4142%3A18020&t=ZaOdyx4fdZjQ3mO6-4) in figma

**Comment by segacy1** [comment]
Hey folks! I wanted to throw another idea into the mix to solve this issue. We can remove the image entirely and add a colored background to the header content so users can see the guide before the fold. Sharing it in Figma[ here](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=4825%3A21633&t=ucgi3A2fCB5aG9IR-4). and in a screenshot below

![Image](https://user-images.githubusercontent.com/33331853/211684482-a3ae1139-b387-4cb9-b2bf-3166ed9ed104.png)

cc: @esquared415, please let us know what you think!

**Comment by segacy1** [comment]
Hey @mrose914 adding the updated designs in [figma](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=3979%3A11994) after our review with Erika. @machikoyasuda, you'll see a new color [primary/dark-blue] and new button style which I've added to the [components](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=4907%3A21418&t=Q8zbZ50kbjAsSlYg-4) and [style](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=3725%3A10998) pages.  

Also, I noticed a bug on mobile where when the table of contents is open the background will scroll but the table of contents won't (including a video)

https://user-images.githubusercontent.com/33331853/213788479-776a73ae-32ae-4f03-88df-9560859bb867.mov
