### ISSUE TITLE
Implement new /how-to/get-connected page

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#401]
Wireframes here: https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=4606%3A20365&t=Xw6FPzkZQzHdUq6g-0

Copy here: https://docs.google.com/document/d/1uLjCTC0LEjaDtOivWQp0OFM0ZVIjULnr_cZ6-QgAi0k/edit#heading=h.hu6tpby747nd

**Comment by machikoyasuda** [comment]
Question: Where does this Complete the Form button link to? @mrose914 

<img width="856" alt="image" src="https://user-images.githubusercontent.com/3673236/213029850-45f146a5-3dcd-492e-88bb-751e9bf5ee2f.png">

**Comment by machikoyasuda** [comment]
@segacy1 Request: Could you send me high-res versions of all the diagrams in this design?

<img width="903" alt="image" src="https://user-images.githubusercontent.com/3673236/213030173-ff5a5376-6796-4e93-af85-57687b8fb03a.png">

**Comment by segacy1** [comment]
Hey @machikoyasuda here are the graphics
[Connectivity Graphics.zip](https://github.com/cal-itp/mobility-marketplace/files/10446315/Connectivity.Graphics.zip)
