### ISSUE TITLE
Redirect NASPO link to new /how-to/get-connected page

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#402]
Blocked on #401

**Comment by machikoyasuda** [comment]
New solution:

- Leave the PDF link available https://www.camobilitymarketplace.org/assets/Cal-ITP.MobilityMarketplace.DataPlans.NASPO.FirstNet.pdf
- Replace the `NASPO` link in the table with https://www.camobilitymarketplace.org/how-to/get-connected
