### ISSUE TITLE
Migrate to Google Analytics 4

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#417]
https://support.google.com/analytics/answer/10759417

> Universal Analytics standard properties will stop processing data on July 1, 2023. To maximize historical data and to ensure that Google Analytics 4 (GA4) meets your specific needs, we recommend you make the switch to Google Analytics 4 now. This will give you the opportunity to customize the setup including using the latest site tag.
> 
> For any customer who does not set up a GA4 property with basic settings, starting in March, we will configure one with a few basic settings consistent with the existing Universal Analytics property; this includes certain conversion events, Google Ads links, and existing website tags.

**Comment by machikoyasuda** [comment]
@mrose914 The Google Analytics 4 migration is complete. Do you mind checking GA from your side to make sure all the stats / events you need for Mobi Mart are available?
