### ISSUE TITLE
Add copy to MobiMart pages that the RFP included all federal clauses

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#418]
- Add the following copy to https://www.camobilitymarketplace.org/contracts/

- Add below first paragraph on the page, but above the GTFS blurb

**How do MSA’s Work?**

The Mobility Marketplace serves as Cal-ITP’s online catalog, where transit
providers can browse available goods and services and build a customized
transit technology system that suits their needs. The contracts or Master
Service Agreements (MSA) listed on this site are examples of a “state
purchasing schedule.” These schedules are agreements between a State or
related entity and a vendor(s) to provide goods or services at agreed upon
prices. Fundamentally, state purchasing schedules are designed to
accommodate other parties who may enter in and benefit from the
agreements in the future.

The Federal Transit Administration (FTA) [supports](https://www.transit.dot.gov/sites/fta.dot.gov/files/docs/Third%20Party%20Contracting%20Guidance%20%28Circular%204220.1F%29.pdf) recipients in pursuing state
purchasing schedules given that agreement parties have granted express
permission and all FTA and Federal requirements are met. More on Third Party
Procurement is available from the FTA [here](https://www.transit.dot.gov/funding/procurement/third-party-procurement/third-party-procurement-faqs).

**Comment by esquared415** [comment]
@mrose914 

_How about this? [Note: I have slightly edited all of these text blocks, to fix typos.]_

Change headline from "CONTACTLESS FARE COLLECTION" to "State of California Contracts"
_[Note: This is the headline when you click through to an individual contract page, such as https://www.camobilitymarketplace.org/contracts/view?contracts-filter-product=Payment%20Processor.]_ 

**Contracts**
The State of California has Master Service Agreements (MSAs) available to help you modernize your transit system. The Mobility Marketplace serves as Cal-ITP’s online catalog, where transit providers can browse available goods and services and build a customized transit technology system that suits their needs.

**How do MSAs Work?**
The contracts or MSAs listed on this site are examples of a “state purchasing schedule.” These schedules are agreements between a state or related entity and vendor(s) to provide goods or services at agreed-upon prices. Fundamentally, state purchasing schedules are designed to accommodate other parties that may enter into and benefit from the agreements in the future.

The Federal Transit Administration (FTA) [supports](https://www.transit.dot.gov/sites/fta.dot.gov/files/docs/Third%20Party%20Contracting%20Guidance%20%28Circular%204220.1F%29.pdf) recipients in pursuing state purchasing schedules, given that agreement parties have granted express permission and all FTA and Federal requirements are met. More on Third Party Procurement is available from the FTA [here](https://www.transit.dot.gov/funding/procurement/third-party-procurement/third-party-procurement-faqs).

**Contactless Fare Collection**
To add contactless fare collection, you will need up to three new technologies and ensure internet connectivity on your fleet (if you don’t already have it).

**Become GTFS-compliant first for best results** _Highly recommended_
We recommend creating an action plan for becoming GTFS-ready before going contactless, as the vendors you select can help you use this data for reporting purposes plus help your customers see your real-time vehicle location and fare information on journey-planning smartphone maps and apps.

**Comment by thekaveman** [comment]
@esquared415 we need to make at least one change, that is the `here` link in **How do MSAs Work?**, suggestion:

```diff
-- More on Third Party Procurement is available from the FTA [here](https://...).
++ Read more about [Third Party Procurement](https://...) from the FTA.
```

Ideally the other link for `supports` should be more descriptive of what the linked resource is, suggestion:

```diff
-- The Federal Transit Administration (FTA) [supports](https://...) recipients in pursuing state purchasing schedules...
++ [Guidance from the Federal Transit Administration (FTA)](https://...) supports recipients in pursuing state purchasing schedules...
```
