### ISSUE TITLE
Fixes: Contact Form

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/mobility-marketplace#433]
These are edits from @segacy1: 

- I’ve added updated designs/states for input fields, checkmarks, and radio buttons [here](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=4268-17731&t=1RYcAOXwQRqdeOgw-4).
- Can we update the padding to be the following (reflected in figma and I can add pics or tag you in specific spots if that’s clearer):
- Radio button selector q's:
- 8px between checkmark/radio button and text
- 4px between each selection
- 8 px between question text and input fields
- 24px btwn each question (dsk), MBL: 20px btwn each question (mbl)
- Can we update the behavior for missing field inputs? Ideally, an alert won’t appear unless the user tries to submit without completing all required forms. If they do, the missing fields will display in their error state and (if possible) the page will jump back up to the first missed field.
- Yes please let’s match the nav/content sitch here to the how-to page!
- Please swap the hero image with this one and hide hero image on mobile:

**Comment by machikoyasuda** [comment]
@AnthonyRollins These are fixes requested by @segacy1 for the /contact page hubspot forms:

1. Make all the text sentence case. So that means `First Name`, `State where Agency is based` should be `First name` and `State where agency is based`, etc.
2. Reformat the `How can we help? (Transit Agency)` question like this:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/3673236/228088459-b20afeca-a195-481d-8093-1533b484677a.png">

Thank you!

cc @segacy1

**Comment by segacy1** [comment]
Hey @machikoyasuda! Sarah and I finalized the primary black & blue we'll use across cal-itp properties. For now, the only change to mobimart is making the black #212121 to match benefits. Would we be able to make that update in this round of edits?

**Comment by AnthonyRollins** [comment]
@machikoyasuda @segacy1 Updated all questions to sentence case. Changed `How can we help? (Transit Agency)` to `Do you want to get in touch about?` 

What about the `Vendor` form? Should we change the question below too, or leave it how it is?
 ![Screenshot 2023-03-28 at 12 44 08 PM](https://user-images.githubusercontent.com/25047205/228349831-61ad9ab0-d2a2-4415-ae3d-53d5c4a1ebd7.png)

**Comment by segacy1** [comment]
@AnthonyRollins yes, let's change it for vendor too. Ty!

**Comment by segacy1** [comment]
@AnthonyRollins Yes, let's change it too. Ty!

**Comment by AnthonyRollins** [comment]
@segacy1 Updated. Let me know if there are any other changes.
