### ISSUE TITLE
SCOPE: Different implementation options for Provider Map

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#440]
Given the [new redesign](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=5601-29511&t=0sznFMu9eKaRxejn-0) of the Provider Map page, we would like to scope out implementation considerations and options for implementing the map, per convo in dev kickoff on 4/13.

**Comment by segacy1** [comment]
@machikoyasuda @mrose914 I broke down the map functionality a little further [here](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=5719-32260&t=R6VlS8K0U9poRjjo-4). The options included are:

1. (MVP) We keep the same functionality that exists today + the table
2. When a user clicks on a provider in the network list they'll see additional specs AND/OR
3. When a user clicks on a location on the map, the location is highlighted
