### ISSUE TITLE
SCOPE: Determine what fields we can implement in "all agencies" view 

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#441]
The data we provide on the [Provider Map page](https://www.camobilitymarketplace.org/provider-map) is from a static csv that was last updated in 2019/2020 and is now out of date. 

Since then, we have developed various other tools and representations of lists of agencies that we feel may be a better fit here and could allow us to keep the list dynamic and up to date without engineering intervention. 

The goal of this ticket is to sync with the data team to determine what views currently exist that may meet our needs and scope out the work that would be required to develop and implement a new source/view.

NOTE: This is not a blocking requirement for the launch of the redesigned page.

**Comment by thekaveman** [comment]
This is finished, @allejo is working on the data pipeline now.
