### ISSUE TITLE
Primary nav overlays main content on medium screen size

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#447]
On a medium screen (e.g. > `767px` and < `992px`) the primary nav goes into the "hamburger" mode, but expanding the menu overlays the main content with a transparent background. 

Here it is right after going from mobile into medium size at `768px` (broken):

<img width="633" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/1783439/cef40d21-7aee-48aa-aedc-849c7322733b">

Here it is one pixel smaller in mobile at `767px` (OK)

<img width="498" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/1783439/e24d7b91-c63f-4209-bb04-10e1bde34d60">

And then beyond the medium size into desktop at `992px` (OK):

<img width="791" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/1783439/020e1e20-ff9e-4364-8330-a704f5bb382a">

**Comment by machikoyasuda** [comment]
The fix for this is changing this line https://github.com/cal-itp/mobility-marketplace/blob/main/src/_sass/components/_header.scss#L33 `@include media-breakpoint-up(md) {`

to `@include media-breakpoint-up(lg) {`
