### ISSUE TITLE
Connectivity Content Refresh August 2023

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#461]
The Connectivity team requests some content and copy changes be made to existing pages. Specific requirements and details will be added 8/25.

**Comment by mlgilbert18** [comment]
Attached are the two main items (and found [here](https://docs.google.com/document/d/1fLqTWTPREv_aid50oyneSlwmLAySlOD6/edit) and [here](https://docs.google.com/document/d/1ghHYbo_HeHaCoBALp-HVNQ8VsQZKAvg3LlpzrWNCvj4/edit) in the drive). Note that we are also working on 2 customer success stories (1 paragraph each). I'll pass those along once the agencies' confirm the contents. I'll pass those along once the agencies' confirm the contents.

[Connectivity FAQ External.docx](https://github.com/cal-itp/mobility-marketplace/files/12432928/Connectivity.FAQ.External.docx)

[Q3 2023 Edits to data plans in Mobi Mart.docx](https://github.com/cal-itp/mobility-marketplace/files/12432925/Q3.2023.Edits.to.data.plans.in.Mobi.Mart.docx)
es (1 paragraph each). I'll pass those along once the agencies' confirm the contents.

**Comment by machikoyasuda** [comment]
For changing the language under `How do I get started?` in this doc (https://docs.google.com/document/d/1ghHYbo_HeHaCoBALp-HVNQ8VsQZKAvg3LlpzrWNCvj4/edit), 

<img width="714" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/3673236/1996daf3-0d17-4e45-b6cb-d52292bc315d">

The link goes to this doc, https://docs.google.com/document/d/1f9mvRPx1Zd2lDJgkIiDQjtVF3uxidFYTOHmRAdxLX88/edit, Self Service Instructions. This doc has outstanding Google Drive comments and has filler placeholder text, like `account manager at XX`. Is this sheet intended to be a page on calitp.org as well, or a PDF, or something else?

**Comment by laurenbrennanrebel** [comment]
> 
We are happy to keep this in the guide format. In order to keep this more general, we would like to please request that Questions #1-5 can be under a new section entitled, "New Data Plan Options". We are in agreement with your changes re: Question 6 under the new section "Switching carriers / Changing plans" and Question 7 moved to the ["How do I get started?"](https://www.camobilitymarketplace.org/how-to/get-connected#how-do-I-get-started) section. The PDF for the Self-Service Instructions (see above comment) could also be linked here in this 'How do I get started' section. If there are any questions to my comments above, please feel free to reach me. Many thanks for your assistance!

**Comment by machikoyasuda** [comment]
@mrose914 @laurenbrennanrebel There are still 8 unresolved comments on the Self-Service Instructions Google Doc

https://docs.google.com/document/d/1f9mvRPx1Zd2lDJgkIiDQjtVF3uxidFYTOHmRAdxLX88/edit

<img width="1326" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/3673236/e529e4ae-1b41-4f81-873c-72023668c04c">
<img width="1382" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/3673236/b69a7270-f828-46db-baeb-00fa4aeaa77e">

**Comment by machikoyasuda** [comment]
@mrose914 @esquared415 Is @esquared415 going to review the copy on the Self-Service Doc as well? https://docs.google.com/document/d/1f9mvRPx1Zd2lDJgkIiDQjtVF3uxidFYTOHmRAdxLX88/edit

**Comment by machikoyasuda** [comment]
@mrose914 Or actually, is the self service doc being included in the new copy at all? It's kinda hard for me to parse thru this mega change log doc, but I don't see it linked.

**Comment by machikoyasuda** [comment]
@mrose914 Okay I went thru the changelog doc and figured it out. These changes from this doc https://docs.google.com/document/d/1ghHYbo_HeHaCoBALp-HVNQ8VsQZKAvg3LlpzrWNCvj4/edit are not reflected in the changelog doc

1. Changing the table
<img width="711" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/3673236/df603ca6-3d16-4041-9b1d-678243de28e0">


2. Changing copy, adding a link. The document linked here has outstanding comments/changes that need to be resolved.
<img width="644" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/3673236/1e37d410-a2ec-4f58-9bc0-5a1c408c41e8">

3. Changing link on Contracts page
<img width="681" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/3673236/3194125b-e322-42ab-8f08-7e25e10bfbe3">

Should these requests be ignored or included?

**Comment by laurenbrennanrebel** [comment]
> @mrose914 @laurenbrennanrebel There are still 8 unresolved comments on the Self-Service Instructions Google Doc
> 
> https://docs.google.com/document/d/1f9mvRPx1Zd2lDJgkIiDQjtVF3uxidFYTOHmRAdxLX88/edit
> 
> <img alt="image" width="1326" src="https://user-images.githubusercontent.com/3673236/264481413-e529e4ae-1b41-4f81-873c-72023668c04c.png"> <img alt="image" width="1382" src="https://user-images.githubusercontent.com/3673236/264481381-b69a7270-f828-46db-baeb-00fa4aeaa77e.png">

Hi there,
Apologies I should have accepted all the changes. I did want to leave the last comment there open to indicate where to link back to the FAQs page. This is otherwise all resolved!

Many thanks,

**Comment by laurenbrennanrebel** [comment]
> @laurenbrennanrebel the changes are available for review in staging here: https://deploy-preview-465--cal-itp-mobility-marketplace.netlify.app/how-to/get-connected#toc-and-content
> 
> I have 2 comments / questions:
> 
> * I wasn't sure about where to add the “New data plan options” section. It would seem to make most sense either after “Choosing a carrier” once FirstNet is already introduced OR at the very bottom of the page, as the last section. The issue with putting it after "Choosing a carrier" is that the questions are very long for that section and thus the headers look a bit messy. I'm proposing adding it as the last section. Lmk your thoughts. (Alternatively we could try to shorten / condense the questions, if possible).
> * Please resolve the open questions [here](https://docs.google.com/document/d/1f9mvRPx1Zd2lDJgkIiDQjtVF3uxidFYTOHmRAdxLX88/edit) so we can upload as a pdf.
> 
> I think that's about it!



Hi there,
Great thank you so much for all your help! For the first point, we can accept the proposal to add "New data plan options" into the last section. Otherwise, the Self Service document is now finalized.
Many thanks!

~Lauren

**Comment by laurenbrennanrebel** [comment]
Hi @mrose914, thanks so much! I checked with the team and we are still waiting on confirmation  / edits from the two agencies. We will revert to you as soon as we receive any updates from them! Many thanks, Lauren
