### ISSUE TITLE
Implement new homepage edits 

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#463]
Designs here: https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?type=design&node-id=6819-1396&mode=design&t=4BtRBjMIZXThxpmP-0

Copy here: https://docs.google.com/document/d/1XLUM0EuFa9-A1icT3rySVEUfyZcohOB0D-NTpla8TtI/edit#heading=h.n4fzxa1e69w7

cc @segacy1 

- [x] #466
- [x] #467
- [x] #468
- [x] #488
- [x] #472

**Comment by machikoyasuda** [comment]
![Image](https://github.com/cal-itp/mobility-marketplace/assets/3673236/b637f5f2-92d7-4c71-8a26-16fcecf96e9d)


- Section one: Remove 2 paragraphs, 1 headline
- Section one: Add View contracts button
- Create new section: Modernize your fleet - Headline, paragraph, 4 agencies, paragraph, button
- Delete Map section, delete modernize your fare collection system section
- Change copy on 2 sections, change button
- Add contact section

**Comment by machikoyasuda** [comment]
I suggest this ticket be broken down into 3 tickets, so they can be done in parallel:

1. Create and add the `Modernize your fleet` section with the 4 agency logos. Estimate: 3
2. Update existing copy / Delete sections: (Section 1 - Remove copy, add View Contracts button, Delete Map section, Delete Modernize your fare section, Change copy on 2 sections, change button style). Estimate: 2
3. Add the Stay up to date contact section. Estimate: 1

cc @angela-tran

**Comment by thekaveman** [comment]
Hi @mrose914, we're focused on deploying the Veterans code out to production for the first half of this week, with our Sprint ending on Tuesday 9/19. 

We can come back to MobiMart over the latter half of the week.

**Comment by thekaveman** [comment]
@mrose914 we talked through some of this today, and noticed that this banner text:

> DGS has issued a Draft Request for Proposals (RFP) for GTFS-Realtime software to enable public transit agencies to provide riders with the real time location of their fleets. Responses are due by 2:00 PM Pacific Time on October 12, 2023. Learn more [here](https://caleprocure.ca.gov/event/77601/0000028520).

Is much longer than what the design supports:

<img width="1117" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/1783439/e94af72b-569f-4396-853f-aba2451d224e">

Was the intention to use this exact text on the banner, or a shortened version? Might it be easier to get DGS to approve a shortened version first?

**Comment by thekaveman** [comment]
@mrose914 I think this will need to be workshopped with Design before we go to implement, likely putting us past this week. These options are all still significantly longer than the single sentence (7 words) in the design.
