### ISSUE TITLE
Homepage: Update existing copy / delete sections

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#467]
## Hero / top section

- [ ] Update "Explore this site to find support..." copy
- [ ] Remove copy "Contracts update!"
- [ ] Remove copy "U.S. public transit providers, we have news for you..."
- [ ] Add View Contracts button in new style

## Lower sections
- [ ] Remove Map section and Modernize section
- [ ] Move up "What is Cal-ITP?" section, and update copy. Move image
- [ ] Replace "Begin taking contactless fare payments" section with "Get in touch" section

**Comment by angela-tran** [comment]
I'm noticing a discrepancy between what's in the [copy document](https://docs.google.com/document/d/1XLUM0EuFa9-A1icT3rySVEUfyZcohOB0D-NTpla8TtI/edit#heading=h.n4fzxa1e69w7) linked from #463 and what we've written in this issue's description (which came from https://github.com/cal-itp/mobility-marketplace/issues/463#issuecomment-1701840702).

The copy document shows that section 1 should still include "Explore this site to find support..." and that the copy has been updated slightly from what's on current MobiMart.

I'm going to use the Google Doc copy and update the issue description.

**Comment by thekaveman** [comment]
> I'm going to use the Google Doc copy

Sounds right! Thank you

**Comment by angela-tran** [comment]
Between version 2 and 3 of this issue's descriptions, we lost the part about "Delete Map section, Delete Modernize your fare section, Change copy on 2 sections". @thekaveman did you want that in a separate ticket?

![image](https://github.com/cal-itp/mobility-marketplace/assets/25497886/6ec88ae2-18b1-4487-8424-d23d1c05bfc6)

<img src="https://github.com/cal-itp/mobility-marketplace/assets/25497886/efd886f4-1d64-4f43-a13f-f4a7cf569ace" width="400">

Also see screenshot from https://github.com/cal-itp/mobility-marketplace/issues/463#issuecomment-1701840702

**Comment by thekaveman** [comment]
Sorry, looks like a bad edit on my part. Feel free to list as tasks here or create new ticket(s) -- whatever makes most sense.
