### ISSUE TITLE
Rewrite the "How to: Get Connected" page as regular HTML or Markdown

### ISSUE THREAD

**Issue by allejo** [cal-itp/mobility-marketplace#469]
The [`/how-to/get-connected`](https://www.camobilitymarketplace.org/how-to/get-connected) page is written as [a YAML file](https://github.com/cal-itp/mobility-marketplace/blob/509405aef7f0d2abfb521b9066b9a91695e4487c/src/_data/how_to/get_connected.yml). Looks like this was done so that [`toc-and-content.html` could generate the table of contents on the left programmatically](https://github.com/cal-itp/mobility-marketplace/blob/509405aef7f0d2abfb521b9066b9a91695e4487c/src/_includes/toc-and-content.html). However, this content can be rewritten and maintained as markdown/HTML while making use of my [jekyll-toc](https://github.com/allejo/jekyll-toc) project to generate the table of contents programmatically.

**Comment by machikoyasuda** [comment]
There's this page that would need to get converted, too: https://github.com/cal-itp/mobility-marketplace/blob/main/src/_data/how_to/go_contactless.yml

https://www.camobilitymarketplace.org/how-to/go-contactless

**Comment by thekaveman** [comment]
@allejo do you think you can get to this in the coming sprint, after all the Provider Map work is complete?
