### ISSUE TITLE
Mobility Marketplace Connectivity Page Copy Updates

### ISSUE THREAD

**Issue by jcbroader** [cal-itp/mobility-marketplace#474]
We'd like the following copy changes 
(on the navigation panel on the left-hand side)
- Choosing how much data -> How much data do I need?
- Choosing a carrier -> Which carriers are available to purchase data plans from?
- Switching plans/Changing carriers -> What if I need to change carriers?
Move this heading and section below the data plan pricing section 
- Data plan pricing -> What are the data plan prices?
In this section, we'd like to edit the table by naming each tier and adding "Tier 1" over <3,000 SIMs, "Tier 2" over 3k-9,999 SIMs, and "Tier 3" over >9,999 SIMs
- Under "My agency is interested in purchasing a FirstNet data plan. How long will a purchase take?" add line "More information and the self-service instructions are available here [link]." (The link should go to the First Net Self Service Instructions PDF which is uploaded in https://github.com/cal-itp/mobility-marketplace/issues/473)

**Comment by jcbroader** [comment]
Can we move the "What are the data plan prices?" section above the "What if I need to change carriers?" one?

**Comment by thekaveman** [comment]
Hi @jcbroader, please submit a new issue since this one is already closed/complete.

**Comment by jcbroader** [comment]
Apologies - I thought this would reopen it. I'll start a new one!

**Comment by thekaveman** [comment]
No worries!

We typically don't want to reopen an issue that was closed by implementing the changes requested in the ticket. Since the work has been completed and deployed into the website, we consider a ticket like this "final", and new changes should be documented in new tickets.

Appreciate it!

**Comment by jcbroader** [comment]
That's good to know - thanks so much!
