### ISSUE TITLE
Reframing FirstNet information 

### ISSUE THREAD

**Issue by jcbroader** [cal-itp/mobility-marketplace#486]
Below are the sections and the corresponding edits we'd like made. 

What are the data plan prices?
- Remove "and Tier II prices are now available to all California agencies!"
- AFter, "In California, ......" add "Interested in tapping these rates? Contact us to get started today! Our team is happy to answer questions and guide you through the process."

What is FirstNet?
- Remove the header and entire section

Why do the FirstNet plans have tiers? What do these tiers mean?
- Change "Cal-ITP worked with FirstNet to create data plans tailored for transit agencies at a competitive price. The tiers incentivize more collective purchases and were designed by FirstNet to enable discounted rates in a way that works for their business case." to "FirstNet created data plans tailored for transit agencies at a competitive price. The tiers incentivize more collective purchases and were designed to enable discounted rates in a way that works for their business case."

Can FirstNet be used for any device and use case?
- Remove "and should be confirmed before purchase."
- After This certification is common....." add "For agencies purchasing hardware devices off of MobiMart, the table below summarizes what networks each device is certified to operate on."
- After the FirstNet contact information, add "If your device is not eligible for FirstNet, you may still be able to get the same rates on the commercial AT&T network. Please contact the FirstNet representatives above to learn more."

My agency is interested in purchasing a FirstNet data plan.
- Remove header and entire section

Where can I access the non-FirstNet data plan rates in the table above?
- Move this question and section to below "What are the data plan prices?"
- Change this section's header to "Where can I access the data plan rates?"
- Add "FirstNet data plan rates are available through the self-service instructions on the Data Plan Procurement Self-Service instructions." (with an embedded link) after "Data plan rates for AT&T, T-Mobile, and Verizon can be found on either CalNet or on NASPO."

**Comment by jcbroader** [comment]
@mrose914 thanks for your help on this! Let me know if it would be helpful to send along the Word Doc with edits

**Comment by thekaveman** [comment]
@machikoyasuda can you please make these changes this week? Marissa folded all the updates inline into the copy changelog: https://docs.google.com/document/d/1XLUM0EuFa9-A1icT3rySVEUfyZcohOB0D-NTpla8TtI/edit#heading=h.f144n7h43n26
