### ISSUE TITLE
Add GTFS-RT RFP announcement

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#493]
The GTFS-RT RFP will be published soon. We would like to add an announcement on MobiMart directing folks to view the RFP. 

**Announcement:** 
DGS has issued a Request for Proposal (RFP) for GTFS-Realtime software and optional hardware to enable public transit agencies to provide riders with the real time location of their fleets. Responses to the RFP are due by February 12, 2024. Learn more [here](https://caleprocure.ca.gov/event/77601/0000029244).

**Comment by machikoyasuda** [comment]
@mrose914 We need to get the approval by Friday 12/22 in the early AM at the latest - and @angela-tran can get to it,, or else, it will have to wait until 1/2/2024. (I don't work on Fridays, and Compiler has a week off after 12/22).

**Comment by machikoyasuda** [comment]
@mrose914 Started a draft of a PR here - https://github.com/cal-itp/mobility-marketplace/pull/514 - so we're extra ready for the final text/link.
