### ISSUE TITLE
[vendor page] Add new header image and link to contact us

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#495]
The goal of this header is to provide an overview of the "story" of MobiMart for a vendor and to provide a clear CTA to contact us, via a button.

![Screen Shot 2023-11-28 at 4 54 40 PM](https://github.com/cal-itp/mobility-marketplace/assets/3137409/97a03ab1-5823-427a-8cd1-efaf34aef382)

**Comment by segacy1** [comment]
Hero graphic is here
[hero-graphic.zip](https://github.com/cal-itp/mobility-marketplace/files/13503139/hero-graphic.zip)
