### ISSUE TITLE
[vendor page] Add new Focus Areas section

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#496]
The goal of the Focus Areas section is to help vendors position themselves in what they may be able to offer Cal-ITP but sharing our high-level goals. 

![Screen Shot 2023-11-28 at 4 53 35 PM](https://github.com/cal-itp/mobility-marketplace/assets/3137409/7c9dbc41-a9e5-436c-8b67-78e73d1c7fba)

**Comment by segacy1** [comment]
Icons here
[stat.zip](https://github.com/cal-itp/mobility-marketplace/files/13503118/stat.zip)

Note: The bounding box for all three icons is 72x72, but the icons have different sizes and placements within the bounding box to make them look aligned with each other
