### ISSUE TITLE
[vendor page] Add new Meet your market section

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#497]
The "Meet your market" section is designed to give vendors a sense of the size and complexity of the CA market, and to direct them to the existing Provider Map via a button. 

![Screen Shot 2023-11-28 at 4 51 13 PM](https://github.com/cal-itp/mobility-marketplace/assets/3137409/ffd019dc-56f0-4c33-81fb-d731fbc96504)

**Comment by segacy1** [comment]
Adding the graphic for this section here
[stat.zip](https://github.com/cal-itp/mobility-marketplace/files/13503061/stat.zip)

**Comment by thekaveman** [comment]
Timebox 1 day to try to implement the graphic with CSS + bus icon

Fall back: really long alt tag with explanation
