### ISSUE TITLE
[vendor page] Add new FAQ section

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#498]
Many vendors contact us and ask "how can we get on MobiMart?". In an effort to direct folks to contact us through the site, where they can provide more info about their inquiry, we have a short set of FAQs on the vendor page. 

![Screen Shot 2023-11-28 at 4 47 45 PM](https://github.com/cal-itp/mobility-marketplace/assets/3137409/a8178d1e-ba55-4974-b5f4-81820669b93e)

**Comment by segacy1** [comment]
Design note: there are some discrepancies in Figma/prod link styling. I created a ticket for myself to update that [here](https://github.com/cal-itp/mobility-marketplace/issues/501), and we can slot that in the backlog for dev once I'm done!

**Comment by thekaveman** [comment]
Let's fix the "here" link
