### ISSUE TITLE
[vendor page] Add new Stay up to date section

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#499]
The new vendor page is designed to provide helpful information to vendors. We should add the existing section we use throughout MobiMart to direct vendors to "stay up to date" by signing up for the newsletter. 

![Screen Shot 2023-11-28 at 4 43 30 PM](https://github.com/cal-itp/mobility-marketplace/assets/3137409/d9accc8e-19b5-42f6-be60-aec037581019)

**Comment by segacy1** [comment]
Design Note: Comparing Figma & prod, I see that the error asterisk* on the site is to the left of the "email" label. Could we create a ticket for the future to update that to what's in figma? (asterisk on the right)
