### ISSUE TITLE
[vendor page] Add link to Vendor page from top nav

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#500]
![Screen Shot 2023-11-28 at 4 39 16 PM](https://github.com/cal-itp/mobility-marketplace/assets/3137409/1637afe1-7d73-4e88-9d68-75ba1c553f2e)

The new vendor page includes a requirement to add "For Vendors" as an option from the MobiMart homepage, specifically in the top nav. 

The rationale for this change is that vendors are a significant segment in terms of users of the site and should be able to quickly access information that may be most useful to them. 

**Acceptance Criteria:** 
After this change is implemented, the top nav should read, from left to right: 

- Products 
- Contracts
- For vendors 
- About 
- Contact us

**Comment by segacy1** [comment]
Design Note: In figma, the desktop nav bar was updated so that:

- each link had 72px between them
- there's a column of whitespace on either side of the nav content

Mobile nav discrepancies are noted in the design backlog (ie - mobile menu icon in Figma to match what's live)
