### ISSUE TITLE
Add Fiserv contracts to MobiMart + minor copy update

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#519]
Requirements: 

Add new row to Contracts > Payment Processors with the following columns:
- Contract: [5-22-70-22-02](https://caleprocure.ca.gov/pages/LPASearch/lpa-details.aspx?Page=ZZ_CTR_SUP_PG&Action=U&ForceSearch=Y&CNTRCT_ID=5-22-70-22-02&SETID=STATE&VERSION_NBR=3)
- Category: Contactless Payment 
- Product: Payment Processor 
- Vendor: Fiserv*

Replace Elavon footnote with *, which should correspond to the same message below, which applies to both rows in the table. 

*: "Available to California agencies only." to "Available to California agencies only. If you are an out of state agency, please reach out to [hello@calitp.org](mailto:hello@calitp.org) to discuss options."

**Comment by jenro1** [comment]
This looks great, thanks Marissa! Is there a way to make the footnote apply to both Elavon and Fiserv, as it's the same situation for both? Perhaps an asterisk?

**Comment by thekaveman** [comment]
@mrose914 @jenro1 is this content ready to go, can we begin working on this this week?
