### ISSUE TITLE
Add new section to Payments Guide

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#520]
We have a [Support Framework presentation](https://drive.google.com/drive/u/0/folders/1twcrdSIykaKhHkozUJT-PaTyCjVDM2Ep) that provides some information on how providers can manage implementation and support questions/troubleshoot common issues. 

We would like to update content to include this resource within the [How To Go Contactless Guide](https://www.camobilitymarketplace.org/how-to/go-contactless).

See changes in the [changelog](https://docs.google.com/document/d/1XLUM0EuFa9-A1icT3rySVEUfyZcohOB0D-NTpla8TtI/edit#heading=h.qu4incxbq95e).

**Comment by jenro1** [comment]
Thanks @mrose914! Just minor text edits in this para:

**Maintenance and support**
Cal-ITP is here to help! Please download and review our [Support Framework] - a document you can fill in and use to provide information to your internal team(s) about roles and responsibilities, common troubleshooting steps, how to manage your vendor relationships and how to monitor key performance outcomes.
