### ISSUE TITLE
New "Draft Scope of Work"

### ISSUE THREAD

**Issue by AngellyTovar** [cal-itp/mobility-marketplace#536]
Can you replace the "MSA SOW Template and Guidance" PDF on this page (https://www.camobilitymarketplace.org/how-to/go-contactless) with the latest version on the Google Drive: https://drive.google.com/file/d/1dAvY1p65aRDMBad-AUHhHG0NXzwOlznC/view?usp=drive_link

**Comment by AngellyTovar** [comment]
> @AngellyTovar thanks for filing. Can you please ensure it passes Adobe's accessibility check as a pdf? I did a quick look and it seems there are a couple of issues that need to be resolved. Lmk if you need any help! Once it passes, please upload to the same link and we can get that posted ASAP.

Did the check and manually fixed the issues on my end: https://drive.google.com/file/d/1dAvY1p65aRDMBad-AUHhHG0NXzwOlznC/view?usp=drive_link

**Comment by AngellyTovar** [comment]
Let's try this again, I'm almost certain I uploaded the wrong file. https://drive.google.com/file/d/1dAvY1p65aRDMBad-AUHhHG0NXzwOlznC/view?usp=sharing

**Comment by allejo** [comment]
PDF has been updated ✅
