### ISSUE TITLE
Investigate indexing issues in Google Search Console

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#549]
We get periodic reports from Google about various site issues, indexing and/or traffic related. See the latest one here: https://search.google.com/search-console/index?resource_id=sc-domain:camobilitymarketplace.org&utm_source=wnc_20237597&utm_medium=gamma&utm_campaign=wnc_20237597&utm_content=msg_110624660&hl=en

Could you help to do the following: 

- Review past reports to determine and confirm primary issues 
- Identify root cause of issues 
- Remediate issues and/or create tickets with information on remediation options

**Comment by thekaveman** [comment]
@allejo I gave you full access to Google Search Console for calitp.org and MobiMart.
