### ISSUE TITLE
Bug: Contact form broken on Firefox

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/mobility-marketplace#557]
<img width="1512" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/3673236/63525e4d-85e5-41eb-a7d7-f9c0e6b56cee">

Newsletter form in the footer area and the Contact page are broken on Firefox. Confirmed not broken on Safari.

Left is Firefox. Right is Chrome.

<img width="1512" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/3673236/4f1bc87f-de58-485b-9ca4-a21a14b71764">

Firefox market share is quite low - 2.75% according to statcounter.com:

<img width="1223" alt="image" src="https://github.com/cal-itp/mobility-marketplace/assets/3673236/cc9bbdf2-8418-4708-9822-2a8a6f0a104e">

**Comment by thekaveman** [comment]
It looks like the Hubspot Javascript library was blocked? Maybe this is a local browser setting/plugin and not an issue per se?

**Comment by machikoyasuda** [comment]
@thekaveman AHH ~ That was it. Refreshed all my Firefox settings. Thank goodness. Closing.
