### ISSUE TITLE
Add Remix announcement banner

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#564]
Once we make the Remix announcement, we should publish a banner to MobiMart including the link to the intake form: 

Cal-ITP is offering a limited number of licenses to Remix’s suite of scheduling products to smaller providers in CA. Check your eligibility using our intake form [ADD LINK].

**Comment by ohmegasquared** [comment]
(for myself - https://deploy-preview-514--cal-itp-mobility-marketplace.netlify.app/)

**Comment by ohmegasquared** [comment]
Confirming banner launch date with Jess -- she thinks 11/20

Copy: Cal-ITP is offering smaller providers in California a limited number of free licenses to Remix’s suite of scheduling products. Check your eligibility and sign up using our intake form.

Link:
https://share.hsforms.com/13WkzY7taSoSdxBATWsNedQ3aanu

Preview: ![Image](https://github.com/user-attachments/assets/d3e92b7e-4ffc-49c5-b176-d797b3af60fa)
