### ISSUE TITLE
Images need alt tags

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#59]
Hard-coded images (e.g. the site logo) should have appropriate `alt` tags hard-coded in as well.

Anything coming out of the CMS needs to carry with it user-generated text to populate an `alt` tag (and this needs to be a required field in the CMS, if an image is being selected/inserted).

**Comment by allejo** [comment]
Going to close this as stale, we're not actively using the CMS anymore (see #294) and all relevant images should have `alt` tags now after #275.
